### PR TITLE
Removed unneeded code

### PR DESCRIPTION
**Pull request by GrantSeltzer**
Removed:

vendor, pkg, man, errors, integration-cli, docs, contrib, Dockerfiles, and few other extraneous things

### CODE REVIEW

**Comment by nalind** [comment]
I think you may have some of the needed modules present on your system elsewhere in your $GOPATH, as your branch doesn't build on my system.  I get complaints from 'hack/make.sh dynbinary' about lack of:
* github.com/Sirupsen/logrus
* github.com/docker/engine-api/types/filters
* github.com/docker/go-units
* github.com/mistifyio/go-zfs
* github.com/opencontainers/runc/libcontainer/label
* github.com/opencontainers/runc/libcontainer/system
* github.com/opencontainers/runc/libcontainer/user
* github.com/vbatts/tar-split/tar/storage
* golang.org/x/net/context

**Comment by GrantSeltzer** [comment]
@nalind Fixed :) Sorry I didn't catch that

**Comment by nalind** [comment]
Hmm, a couple of things restored in unexpected places:
* vendor/src/github.com/runc should be vendor/src/github.com/opencontainers/runc
* vendor/src/github.com/golang.org should be vendor/src/golang.org
It looks like we also need to restore:
* github.com/docker/engine-api/types/versions
* github.com/pborman/uuid

**Comment by GrantSeltzer** [comment]
Fixed that, not sure how I got a duplicate runc in the github.com directory.

**Comment by nalind** [comment]
I think vendor/src/github.com/opencontainers/runc is still missing...?

**Pull request closed without merging**
