### PR TITLE
Added kerberos authentication integration tests.

### PR DESCRIPTION
**Pull request by lioryanko**
Signed-off-by: Lior Yankovich <lior@twistlock.com>

### CODE REVIEW

**Comment by nalind** [comment]
Cherry-picked and merged.  Thanks!

**Comment by lioryanko** [comment]
Heh, actually I made those fixes about a week ago. I didn't push it because in order to avoid multiple rebases, I wanted to push it along with the Basic integration tests.
Was waiting for you to add automation support before starting to write tests for Basic authn. I now realize that you changed the commit history, that's why I missed the fact that you already added support for that.

Anyways, good job!

**Comment by nalind** [comment]
Ah.  Whoops.  I had to rework the command-line hook stuff in the client to actually make it work in the tests -- apparently, getting the added client options to show up in the --help output wasn't enough, after all.  If the Basic tests you were adding work differently than what's there, adding them shouldn't hurt (especially if you're exercising things with zero-length user name or password), so if you like, go ahead and open a PR for them.  I haven't got any functional changes planned unless you or commenters in the authentication PR need them, or we need to resolve conflicts with master.

**Comment by lioryanko** [comment]
No, it's fine. I didn't actually write any Basic tests yet.

**Pull request closed without merging**
